version: '3'
services:
# the frontend makes the site publicly available
  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - geoservices
    # TODO environment variables for backend and geoservices urls
    volumes:
      - ./frontend/app:/usr/src/app
      - ./frontend/server.js:/usr/src/server.js
      - ./server.cert:/usr/server.cert
      - ./server.key:/usr/server.key
    command: npm start

# web services
# TODO uncomment this section when backend is ready to run inside docker instead of running from STS
  backend:
    image: openjdk:latest
    ports:
      - "8888:8888"
    depends_on:
      - backend_db
    volumes:
      - ./backend/target/backend-0.0.1-SNAPSHOT.jar:/usr/app/app.jar
      - ./keystore.p12:/usr/keystore.p12
    environment:
      - POSTGRES_HOST=backend_db
    command: bash -c "cd /usr/app && java -jar app.jar"
  geoservices:
    image: openjdk:latest
    ports:
      - "9999:9999"
    depends_on:
      - postgis
      - mongodb
    volumes:
      - ./GeoServices/target/GeoServices-0.0.1-SNAPSHOT.jar:/usr/app/app.jar
      - ./keystore.p12:/usr/keystore.p12
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_PORT=5432
      - MONGO_HOST=${MONGO_HOST:-mongodb}
    command: bash -c "cd /usr/app && java -jar app.jar"
