version: '3'
services:
# the frontend makes the site publicly available
  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - geoservices
    # TODO environment variables for backend and geoservices urls
    volumes:
      - ./frontend/app:/usr/src/app
      - ./frontend/server.js:/usr/src/server.js
    command: npm start

# web services
# TODO uncomment this section when backend is ready to run inside docker instead of running from STS
  backend:
    image: openjdk:latest
    ports:
      - "8888:8888"
    depends_on:
      - backend_db
    volumes:
      - ./backend/target/backend-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      - POSTGRES_HOST=backend_db
      # self-knowledge (taken from outer environment and passed to container)
      - BACKEND_HOST
    command: java -jar /app/app.jar
  geoservices:
    image: openjdk:latest
    ports:
      - "9999:9999"
    depends_on:
      - postgis
      - mongodb
    volumes:
      - ./GeoServices/target/GeoServices-0.0.1-SNAPSHOT.jar:/app/app.jar
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_PORT=5432
      - MONGO_HOST=mongodb
    command: java -jar /app/app.jar
    #command: tail -f /dev/null